# Generated by Django 6.0.1 on 2026-01-30 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApproveUsers', models.BooleanField(default=False)),
                ('ViewReports', models.BooleanField(default=False)),
                ('GenerateReports', models.BooleanField(default=False)),
                ('ViewDashboard', models.BooleanField(default=False)),
                ('ViewCalibrations', models.BooleanField(default=False)),
                ('ViewInventory', models.BooleanField(default=False)),
                ('ModifyInventory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('COLAB', 'Colaborador'), ('VISIT', 'Visitante')], default='VISIT', max_length=10)),
                ('permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.permissions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
