# Generated by Django 6.0.1 on 2026-02-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='ViewFillData',
            field=models.BooleanField(default=False),
        ),
    ]
