# Generated by Django 6.0.1 on 2026-02-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_permissions_banusers_permissions_createcalibrations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='ViewCalculator',
            field=models.BooleanField(default=False),
        ),
    ]
