# Generated by Django 5.2.8 on 2025-11-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataSensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='suscription_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
