# Generated by Django 5.2.8 on 2025-11-29 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fill', '0001_initial'),
        ('dataSensor', '0002_alter_sensor_suscription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='fill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Fill.fill'),
        ),
    ]
