# Generated by Django 5.2.8 on 2025-11-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('userId', models.FloatField()),
                ('sensorId', models.FloatField()),
                ('params', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('result', models.TextField()),
                ('previous_calibration', models.DateField()),
            ],
        ),
    ]
