# Generated by Django 5.2.8 on 2025-11-29 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FillPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_solids', models.FloatField()),
                ('total_volatile_solids', models.FloatField()),
                ('potencial_production', models.FloatField()),
                ('max_mu', models.FloatField()),
                ('solvent_volume', models.FloatField()),
                ('initial_concentration', models.FloatField()),
                ('specific_mu', models.FloatField()),
                ('cumulative_production', models.JSONField(blank=True, default=list)),
                ('derivative_production', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.DateField(auto_now_add=True)),
                ('last_day', models.DateField(blank=True, null=True)),
                ('people_involved', models.TextField(blank=True, null=True)),
                ('filling_mass', models.FloatField()),
                ('approx_density', models.FloatField()),
                ('added_watter', models.FloatField()),
                ('type_material', models.FloatField()),
                ('filling_moisture', models.FloatField()),
                ('delay_time', models.FloatField()),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Fill.fillprediction')),
            ],
        ),
    ]
