# Generated by Django 5.2.8 on 2025-11-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplyName', models.CharField(max_length=200)),
                ('TS', models.FloatField()),
                ('VSTS', models.FloatField()),
                ('potencial_production', models.FloatField()),
            ],
        ),
    ]
