# Generated by hand to remove obsolete permission fields
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisos',
            name='VerRecursos',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='SubirRecursos',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='DescargarRecursos',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='InteractuarChatbot',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='VerDocumentacion',
        ),
    ]
